name: gazeprune
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - pip:
    - torch
    - torchvision
    - transformers
    - huggingface_hub
    - datasets
    - qwen-vl-utils
    - opencv-python
    - Pillow
    - numpy
    - matplotlib
    - tqdm
    - bert-score
